language: ruby

sudo: false

env:
  global:
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

matrix:
  include:
    - env: OSX=10.11 HOMEBREW_RUBY=2.0.0
      os: osx
      osx_image: xcode7.3
      rvm: system
    - env: OSX=10.10 HOMEBREW_RUBY=2.0.0
      os: osx
      osx_image: xcode7.1
      rvm: system
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gem

install: true # skip install step

before_script:
  - . ci/travis/before_script.sh

script:
  - . ci/travis/script.sh
