name: Sync CI config from `homebrew/cask`.

on:
  push:
    paths:
      - .github/workflows/sync-ci-config.yml
    branches:
      - main
  schedule:
    - cron: '33 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone secondary repository
        uses: actions/checkout@v4
        with:
          repository: Homebrew/homebrew-cask
          path: homebrew-cask
          persist-credentials: false

      - name: Copy CI config
        run: |
          cp -f homebrew-cask/.github/workflows/ci.yml .github/workflows/ci.yml
          rm -r homebrew-cask

      - name: Generate app token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@5da4e80e7bed9162b1c2d240c5920719611b04bf
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: sync-ci-config
          title: Synchronize CI configuration from `homebrew/cask`.
          body: >
            This pull request was created automatically by the
            [`sync-ci-config`](https://github.com/reitermarkus/homebrew-tap/blob/master/.github/workflows/sync-ci-config.yml)
            workflow.
          commit-message: Update `ci.yml`.
          author: Markus Reiter <me@reitermark.us>
